### ISSUE TITLE
Logo ideas?

### ISSUE THREAD

**Issue by prologic** [openknot/openknot#5]
We need one :)

**Comment by dhutty** [comment]
something from knotwork, perhaps: 
https://en.wikipedia.org/wiki/Trefoil_knot
https://en.wikipedia.org/wiki/Triquetra

**Comment by prologic** [comment]
:+1: on [Trefoil](https://en.wikipedia.org/wiki/Triquetra) :)

**Comment by dhutty** [comment]
On 7/14/15 15:58, James Mills wrote:

> :+1: on [Trefoil](https://en.wikipedia.org/wiki/Triquetra) :)

wait, which? trefoil knot or triquetra?

## 

Duncan Hutty
http://www.allgoodbits.org

**Comment by prologic** [comment]
Oops linked the wrong one, Trefoil,

On Wednesday, 15 July 2015, dhutty notifications@github.com wrote:

> On 7/14/15 15:58, James Mills wrote:
> 
> > :+1: on [Trefoil](https://en.wikipedia.org/wiki/Triquetra) :)
> 
> wait, which? trefoil knot or triquetra?
> 
> ## 
> 
> Duncan Hutty
> http://www.allgoodbits.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openknot/openknot/issues/5#issuecomment-121364250.

## 

James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by dhutty** [comment]
Then go ahead, use this: https://en.wikipedia.org/wiki/Trefoil_knot#/media/File:Blue_Trefoil_Knot.png
It's marked as public domain.
